[package]
name = "hytch-client"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "hytch_client"

[dependencies]
hytch-proto = { path = "../proto" }
hytch-session = { path = "../session" }
tokio.workspace = true
tokio-util.workspace = true
bytes.workspace = true
rustix.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
tokio-stream = "0.1"
