[package]
name = "hytch-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "hytch_proto"

[dependencies]
bytes.workspace = true
tokio-util.workspace = true

[dev-dependencies]
proptest.workspace = true
criterion.workspace = true

[[bench]]
name = "codec"
harness = false
